//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsAppEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OkulContainer : DbContext
    {
        public OkulContainer()
            : base("name=OkulContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ogrenci> OgrenciSet { get; set; }
        public virtual DbSet<Sehirler> SehirlerSet { get; set; }
        public virtual DbSet<Dersler> DerslerSet { get; set; }
        public virtual DbSet<AlinanDersler> AlinanDerslerSet { get; set; }
    }
}
