//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class altMenuS
    {
        public int altMenuS1 { get; set; }
        public string altMenuName { get; set; }
        public int MenuId { get; set; }
    
        public virtual MenuS MenuS { get; set; }
    }
}
