//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detay
    {
        public int dId { get; set; }
        public int sId { get; set; }
        public int pId { get; set; }
        public decimal fiyat { get; set; }
        public Nullable<int> indirim { get; set; }
        public int miktar { get; set; }
    
        public virtual Siparis Siparis { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
