//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int userid { get; set; }
        public string email { get; set; }
        public string pasword { get; set; }
        public Nullable<bool> isLogin { get; set; }
    }
}
